### ISSUE TITLE
Implement Mongo Database

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#11]
1. Get familiar with [mongoengine](http://mongoengine.org/)
2. Take the datatypes defined in the design document and build it into a mongoengine schema. This has been mostly done already [here](https://github.com/Waidhoferj/CSC-308-309-Project/blob/main/Research/graphql-project/models.py).
3. Create a mongodb instance and connect it to mongoengine.
4. Make sure you can create, update and delete objects in the database using mongoengine

Resources:
- [mongoengine getting started](http://docs.mongoengine.org/tutorial.html)

**Comment by Waidhoferj** [comment]
5 hrs

**Comment by Braden50** [comment]
3 hours thus far

**Comment by Braden50** [comment]
Actual time:  6 hours
