### ISSUE TITLE
Report Artwork and Art Review page doesn't scroll

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#111]
When the screen is smaller than the page content, the Report Artwork page should scroll for smaller viewports. Currently, the overflow is hidden and scrolling is disabled.
![GeoArt](https://user-images.githubusercontent.com/33008436/117478721-5c704380-af14-11eb-8056-9acdefbe5348.jpeg)

**Comment by kyleshare** [comment]
Actual time < 1 hour
