### ISSUE TITLE
Build GraphQL Schema in Graphene

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#12]
Make functions for CRUD operations of every item in data design doc

**Comment by Waidhoferj** [comment]
5 hrs

**Comment by Braden50** [comment]
Currently taking 8+ hours. The completion of this issue requires more discussion to be had about functionality and how to store data. It also requires knowledge of how all the app's components stick together through the frameworks which is quite difficult to manage and fully understand.

In the meantime, I've researched a lot about geospatial indexes and how to save images (each their own issue) and simple implementations of the database can now be implemented in the frontend

**Comment by Braden50** [comment]
**This issue took me much more than 8 hours**. This was definitely defined too generally when we were beginning our project. With that said, all of the tasks within this needed to be done and the only way I could think of decomposing it would be to break it up into different types of mutations. I would've done all this work anyways in order, so this decomposition would just be for the purpose of accurate time estimates.
