### ISSUE TITLE
Add Photos to Previously Discovered Artworks

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#123]
On the `Artwork` page, allow the user to take additional photos and upload them to that artwork by clicking on the camera button at the bottom of the page.

## User Flow
1. Go to artwork page.
2. Click on camera button.
3. Take photos.
- View Photos in photo library before submitting.
4. Press submit button.
5. Images uploaded.
6. Get rerouted to the artwork page.

**Comment by gwholland3** [comment]
3 hours
