### ISSUE TITLE
Zooming to pin doesn't center pin on screen with iOS Safari

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#129]
## Steps to Reproduce
1. Go to `ArtMap` on iPhone
2. Click on an Artwork pin
3. Notice that the pin is concealed by the card after zoom in.

**Expected Behavior:** Clicking on a pin should center the pin on the visible part of the map screen.

**Comment by gwholland3** [comment]
0.5 hours
