### ISSUE TITLE
Refine User Stories

### ISSUE THREAD

**Issue by kyleshare** [Waidhoferj/CSC-308-309-Project#13]
Write more relevant and detailed user stories now that we have a more clear direction of the project.

**Comment by Waidhoferj** [comment]
1 hr

**Comment by Waidhoferj** [comment]
Updated user stories at the bottom of [the doc](https://docs.google.com/document/d/1I3DEr58jrW5UJJ6x8Zl-Vsbx41bpCKrg8_8o6eChMAE)

**Comment by gwholland3** [comment]
Took half an hour
