### ISSUE TITLE
Add ability to upload profile pic

### ISSUE THREAD

**Issue by Braden50** [Waidhoferj/CSC-308-309-Project#143]
Users currently can't upload a profile pic, we should give them the option to even though other people currently don't have the ability to view their profile

**Comment by Waidhoferj** [comment]
This should be done through the Profile page and the SignUp page.
- Sign in has optional button for uploading profile pic
- Clicking the profile image on the profile page allows you to upload new pic and replace old one.

**Comment by gwholland3** [comment]
5 hours
