### ISSUE TITLE
Art Submission Page

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#17]
Create the page detailed in the wireframe. Minimum spec:
- Page title
- Input Artwork Name
- Input Rating
- Input Description
- Submission button

**Comment by Waidhoferj** [comment]
Resources:
- [React Hook Form](https://react-hook-form.com/get-started): Library for building and validating forms with minimal code. You'll want to `npm install react-hook-form` on your branch.
- [React Router](https://reactrouter.com): You can use the hook `useHistory` to move between pages. You'll need this to navigate away on form submission.
- [ Framer Motion](https://www.framer.com/motion/): In case you want to animate something
- [Feather Icons](https://feathericons.com/)

**Comment by kyleshare** [comment]
Has taken 6 hours so far. (In progress)

**Comment by kyleshare** [comment]
Worked 3 more hours.

**Comment by Waidhoferj** [comment]
Took 3 hours from where I picked up
