### ISSUE TITLE
Discovered Art Display Page

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#25]
A page to show artwork that has been discovered by the community. It is what the user sees when they follow the compass and arrive at the artwork.
- Display photo up top
- Art description
- Metrics
- Rating component (should already be in project)
- Links out to rating, discussion and report page

**Comment by Waidhoferj** [comment]
Reevaluated remaining time from 8+ to 3 hrs

**Comment by gwholland3** [comment]
8 hours
