### ISSUE TITLE
Report Content Page

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#73]
Create a page that allows users to report an artwork as inappropriate.
Should have:
- Description
- A dropdown category: duplicate, inappropriate, not art.
- Submit button

**Comment by Waidhoferj** [comment]
Plus backend Report object that stores a list of reports

**Comment by Braden50** [comment]
Actual time: 5 hours +

John helped me quite a bit on the frontend, but I still ran into bugs in the backend that took a while to fix.
