### ISSUE TITLE
Add OAuth to application

### ISSUE THREAD

**Issue by kyleshare** [Waidhoferj/CSC-308-309-Project#75]
Research and add authorization protocol to application to remember users' credentials. Allow queries to backend.

**Comment by Waidhoferj** [comment]
Seems like oAuth might be a bit overkill for what we need. Looks like Netlify has a service that's bundled with our site deployment: https://docs.netlify.com/visitor-access/identity/

**Comment by gwholland3** [comment]
Ok, we can discuss it tomorrow then
