### ISSUE TITLE
Implement more reliable primary keys for Groups and Artworks

### ISSUE THREAD

**Issue by Braden50** [Waidhoferj/CSC-308-309-Project#77]
As of right now, Artworks and Groups don't have a reliable primary key. We are just using the titles.

For artwork, we could try using the location (I think I spent some time trying to get this to work and couldn't, might have to be implemented in combo with geo-queries).

For groups, we could make it the name (where it is right now) but that would limit others from making groups of similar names which could be something we want I don't know exactly.

If no existing attributes work then we might have to add our own id attribute.

**Comment by kyleshare** [comment]
Would this be fine as a key if we don't allow for duplicate artwork titles or groups?

**Comment by gwholland3** [comment]
Irrelevant
