### ISSUE TITLE
Art Display Page

### ISSUE THREAD

**Issue by Braden50** [Waidhoferj/CSC-308-309-Project#8]
We are expecting to be able to only have the user be able to see a piece of art when they are within a certain radius of it. This means that we need to define a separate page from the "compass" one when given certain conditions. If these conditions aren't met then this page will no longer be shown.

Note: It is possible that the user could be within two pieces of art at a time. Decisions should be made on how to handle this.

**Comment by Waidhoferj** [comment]
3 hrs
