### ISSUE TITLE
Screen Layout

### ISSUE THREAD

**Issue by Waidhoferj** [Waidhoferj/CSC-308-309-Project#9]
Map out screen layout and UX flow. The screens don't have to have a clear design, but they should have a description of what happens on each screen and how they connect to each other.

**Comment by Waidhoferj** [comment]
3 hrs

**Comment by gwholland3** [comment]
First Draft: https://framer.com/share/Wireframing--gsKx6BvxCiPsUeIGlnqr/z3TC9SJ5A

**Comment by Waidhoferj** [comment]
Took 5 hrs
